# Generated by Django 4.1.6 on 2023-03-20 21:24

import appform.models
import appform.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0002_alter_discorduser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=appform.models.func, max_length=20, unique=True, verbose_name='Номер заявки')),
                ('mail', models.EmailField(max_length=100, validators=[appform.validators.validate_mail], verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=50, validators=[appform.validators.validate_name], verbose_name='ФИО')),
                ('op', models.CharField(choices=[('ИВТ', 'ИВТ'), ('ИТСС', 'ИТСС'), ('КБ', 'КБ'), ('ПМ', 'ПМ'), ('ИБ', 'ИБ'), ('Другое', 'Другое')], max_length=6, validators=[appform.validators.validate_op], verbose_name='ОП')),
                ('course', models.CharField(choices=[('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('4 курс', '4 курс'), ('1 курс (магистратура)', '1 курс (магистратура)'), ('2 курс (магистратура)', '2 курс (магистратура)'), ('Аспирантура', 'Аспирантура'), ('Сотрудник', 'Сотрудник')], max_length=25, validators=[appform.validators.validate_course], verbose_name='Курс')),
                ('project_name', models.CharField(max_length=50, validators=[appform.validators.validate_project_name], verbose_name='Название проекта или КР/ВКР')),
                ('teach_name', models.CharField(max_length=50, validators=[appform.validators.validate_teach_name], verbose_name='ФИО Научного руководителя')),
                ('phone', models.CharField(max_length=20, validators=[appform.validators.validate_phone], verbose_name='Телефон')),
                ('dmodel', models.FileField(upload_to='3dmodels/', validators=[appform.validators.validate_dmodel], verbose_name='3D модель')),
                ('note', models.FileField(upload_to='notes/', validators=[appform.validators.validate_note], verbose_name='Скан служебной записки')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий к заявке')),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('В обработке', 'В обработке'), ('В работе', 'В работе'), ('Ожидает получения', 'Ожидает получения'), ('Отклонен', 'Отклонен'), ('Выполнен', 'Выполнен')], default='На рассмотрении', max_length=30, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oauth.discorduser')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
