# Generated by Django 4.1.6 on 2023-03-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='course',
            field=models.CharField(blank=True, choices=[('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('4 курс', '4 курс'), ('1 курс (магистратура)', '1 курс (магистратура)'), ('2 курс (магистратура)', '2 курс (магистратура)'), ('Аспирантура', 'Аспирантура'), ('Сотрудник', 'Сотрудник')], max_length=25, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='dmodel',
            field=models.FileField(blank=True, upload_to='3dmodels/', verbose_name='3D модель'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='note',
            field=models.FileField(blank=True, upload_to='notes/', verbose_name='Скан служебной записки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='op',
            field=models.CharField(blank=True, choices=[('ИВТ', 'ИВТ'), ('ИТСС', 'ИТСС'), ('КБ', 'КБ'), ('ПМ', 'ПМ'), ('ИБ', 'ИБ'), ('Другое', 'Другое')], max_length=6, verbose_name='ОП'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название проекта или КР/ВКР'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='teach_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ФИО Научного руководителя'),
        ),
    ]
