# Generated by Django 4.1.6 on 2023-03-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0002_alter_articles_course_alter_articles_dmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Комментарий к заявке'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='course',
            field=models.CharField(choices=[('1 курс', '1 курс'), ('2 курс', '2 курс'), ('3 курс', '3 курс'), ('4 курс', '4 курс'), ('1 курс (магистратура)', '1 курс (магистратура)'), ('2 курс (магистратура)', '2 курс (магистратура)'), ('Аспирантура', 'Аспирантура'), ('Сотрудник', 'Сотрудник')], max_length=25, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='dmodel',
            field=models.FileField(upload_to='3dmodels/', verbose_name='3D модель'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='note',
            field=models.FileField(upload_to='notes/', verbose_name='Скан служебной записки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='op',
            field=models.CharField(choices=[('ИВТ', 'ИВТ'), ('ИТСС', 'ИТСС'), ('КБ', 'КБ'), ('ПМ', 'ПМ'), ('ИБ', 'ИБ'), ('Другое', 'Другое')], max_length=6, verbose_name='ОП'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='Название проекта или КР/ВКР'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('В обработке', 'В обработке'), ('В работе', 'В работе'), ('Ожидает получения', 'Ожидает получения'), ('Отклонен', 'Отклонен'), ('Выполнен', 'Выполнен')], default='На рассмотрении', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='teach_name',
            field=models.CharField(max_length=50, verbose_name='ФИО Научного руководителя'),
        ),
    ]
