# Generated by Django 4.1.6 on 2023-04-01 20:03

import appform.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0002_alter_articles_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='mail',
            field=models.EmailField(max_length=100, validators=[appform.validators.validate_mail], verbose_name='Электронная почта'),
        ),
    ]
