# Generated by Django 4.1.6 on 2023-04-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0003_articles_time_created_alter_articles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
