# Generated by Django 4.1.6 on 2023-04-05 16:37

from django.db import migrations, models
import oauth.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100, null=True)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', oauth.managers.DiscordUserOAuth2Manager()),
            ],
        ),
    ]
