# Generated by Django 4.1.6 on 2023-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
