# Generated by Django 4.1.6 on 2023-03-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
