# Generated by Django 4.1.6 on 2023-04-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_discorduser_discord_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar',
            field=models.CharField(max_length=100, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='discord_tag',
            field=models.CharField(max_length=100, unique=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Пользователь активирован'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Последний раз заходил'),
        ),
    ]
